---
- name: Install Nginx on AWS EC2
  hosts: instance2
  become: yes
  tasks:

  - name: Install Nginx (Ubuntu/Debian)
    apt:
      name: nginx
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Start Nginx and enable on boot
    service:
      name: nginx
      state: started
      enabled: yes
